### PR TITLE
WIP: Display only by the labels & remove prov types 

### PR DESCRIPTION
**Pull request by natachaperez**
Previously we had : 
nfo filename
dct format
Screenshot from 2019-07-01 10-28-16

We want to get rid of the prefixes before the labels. Hence, we must add new lines on the nidm-results.owl file to specify the uri of each of these labels for subsequent reading by create_nidmr_context.py. 
On the ontology, I added: 
<http://www.w3.org/2004/02/skos/core#prefLabel> "name of the label"
Then, that will be read and treat into: 
for s, o in sorted(owl.graph.subject_objects(SKOS['prefLabel'])):

### CODE REVIEW

**Comment by cmaumet** [comment]
Thanks @natachaperez! Let me know when this is ready for review.

**Comment by natachaperez** [comment]
@cmaumet I think this is ready for review now.

**Comment by cmaumet** [comment]
@natachaperez: Unfortunately, it looks like the PEP8 issues are back (might be due to your text editor...). Can you try and solve them again? I've added PEP8-speaks to this repository so you should get a message with your next update checking for PEP8 compliance. Thanks in advance!

**Comment by natachaperez** [comment]
Les modifications que j'ai faites sont uniquement pour le fichier .owl or pep8 s'applique pour les fichiers python. Ensuite, en activant le module pep8 sur spyder il m'indique certaines erreurs dues à un non respect de la norme PEP8 que j'ai pour la plupart résolu mais certaines persistent du type : E251 et W291 (dans refresh.py). 

Natacha 
-- 
Natacha Perez, Stagiaire 
Équipe EMPENN 
INRIA Rennes-Bretagne Atlantique 
Campus Beaulieu 
natacha.perez@inria.fr

**Comment by natachaperez** [comment]
Here we work on templates files .txt to remove the general types coming from the PROV Datatype model (prov:entity, prov:agent and prov: activity) and only keeping the specific types (e.g. the nidm types especially). Indeed, while keeping both of the types, there is an ambiguity when the json document is created because there is no preference between both of them. 

Screenshot from 2019-07-02 15-34-47

**Comment by cmaumet** [comment]
Thank you @natachaperez! Looks good!

**Pull request merged**
